# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# pool:
#   vmImage: ubuntu-latest

stages:
  - stage: testing
    displayName: Testing
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: 
        steps:
        - task: NodeTaskRunnerInstaller@0
          inputs:
           nodeVersion: '16'

        - task: Npm@1
          displayName: 'npm ci'
          inputs:
            command: ci

        - task: Npm@1
          displayName: 'npm test'
          inputs:
            command: custom
            workingDir: src
            customCommand: test

  - stage: lint
    displayName: lint
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: 
        steps:
        - task: NodeTaskRunnerInstaller@0
          inputs:
           nodeVersion: '16'

        - task: Npm@1
          displayName: 'npm ci'
          inputs:
            command: ci

        - task: Npm@1
          displayName: 'npm lint'
          inputs:
            command: custom
            workingDir: src
            customCommand: run lint

  - stage: Docker
    displayName: Docker Build and Push
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: 
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerhub'
              repository: 'srikanth1805/demoimage'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: 
                $(Build.BuildId)
          # - task: Docker@2
          #   inputs:
          #     containerRegistry: 'dockerhub'
          #     repository: 'devsecops/demoimage'
          #     command: 'push'
          #     Dockerfile: '**/Dockerfile'
          #     tags: 
          #       $(Build.BuildId)

                

