# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: testing
    displayName: Testing
    jobs:
      - job: 
        steps:
        - task: NodeTaskRunnerInstaller@0
          inputs:
           nodeVersion: '16'

        - task: Npm@1
          displayName: 'npm ci'
          inputs:
            command: ci

        - task: Npm@1
          displayName: 'npm test'
          inputs:
            command: custom
            workingDir: src
            customCommand: test



